{% set name = "xarray-subset-grid" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xarray_subset_grid-{{ version }}.tar.gz
  sha256: 983c24983ca230e5a8ad7f21bf669e8d51bc10a51045602ad37b1886a2baffb3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=72
    - setuptools-scm >=8
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - cf-xarray
    - cftime
    - dask-core
    - netcdf4
    - numpy
    - xarray >=2024.6

test:
  imports:
    - xarray_subset_grid
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/ioos/xarray-subset-grid
  summary: Subset Xarray datasets in time and space
  description: |
    xarray_subset_grid is a single API that provides subsetting of large
    gridded datasets, such as those provided by oceanographic models. It
    provides a single API that supports Rectangular, Unstructured and
    Curvilinear grids. It can work with large xarray datasets, such as those
    backed by zarr and kerchunk.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://xarray-subset-grid.readthedocs.io/en/latest/
  dev_url: https://github.com/ioos/xarray-subset-grid

extra:
  recipe-maintainers:
    - ChrisBarker-NOAA
